/*
 * ADC_Config.h
 *
 *  Created on: 4 Apr 2023
 *      Author: Youssef
 */

#ifndef MCAL_ADC_ADC_CONFIG_H_
#define MCAL_ADC_ADC_CONFIG_H_

/*OPTIONS FOR REF VOLTAGE:
 * 1-ADC_REF_VOLTGAE_AREF
 * 2-ADC_REF_VOLTGAE_AVCC
 * 3-ADC_REF_VOLTGAE_2.56
 */
#define ADC_REF_VOLTAGE_SELECT ADC_REF_VOLTGAE_AVCC

/*OPTIONS FOR RESULT ADJUST:
 * 1-ADC_8BIT_ADJUST
 * 2-ADC_10BIT_ADJUST
*/
#define ADC_ADMUX_RESULT_ADJUST		ADC_10BIT_DATA

/*OPTIONS FOR PRESCALER:
 * 1-ADC_PRESCALER_2_DIVISION
 * 2-ADC_PRESCALER_4_DIVISION
 * 3-ADC_PRESCALER_8_DIVISION
 * 4-ADC_PRESCALER_16_DIVISION
 * 5-ADC_PRESCALER_32_DIVISION
 * 6-ADC_PRESCALER_64_DIVISION
 * 7-ADC_PRESCALER_128_DIVISION
 */
#define ADC_ADCSRA_PRESCALER_SELECT	ADCSRA_PRESCALER_128_DIVISION

/* Options FOR Channel Selection:
 *1-ADC_MUX_SINGLE_PIN0
 *2-ADC_MUX_SINGLE_PIN1
 *3-ADC_MUX_SINGLE_PIN2
 *4-ADC_MUX_SINGLE_PIN3
 *5-ADC_MUX_SINGLE_PIN4
 *6-ADC_MUX_SINGLE_PIN5
 *7-ADC_MUX_SINGLE_PIN6
 *8-ADC_MUX_SINGLE_PIN7
 *9-ADC_MUX_DIFF_PIN0_PIN_0_GAIN10
 *10-ADC_MUX_DIFF_PIN1_PIN_0_GAIN10
 *11-ADC_MUX_DIFF_PIN0_PIN_0_GAIN200
 *12-ADC_MUX_DIFF_PIN1_PIN_0_GAIN200
 *13-ADC_MUX_DIFF_PIN2_PIN_2_GAIN10
 *14-ADC_MUX_DIFF_PIN3_PIN_2_GAIN10
 *15-ADC_MUX_DIFF_PIN2_PIN_2_GAIN200
 *16-ADC_MUX_DIFF_PIN3_PIN_2_GAIN200
 *17-ADC_MUX_DIFF_PIN0_PIN_1_GAIN1
 *18-ADC_MUX_DIFF_PIN1_PIN_1_GAIN1
 *19-ADC_MUX_DIFF_PIN2_PIN_1_GAIN1
 *20-ADC_MUX_DIFF_PIN3_PIN_1_GAIN1
 *21-ADC_MUX_DIFF_PIN4_PIN_1_GAIN1
 *22-ADC_MUX_DIFF_PIN5_PIN_1_GAIN1
 *23-ADC_MUX_DIFF_PIN6_PIN_1_GAIN1
 *24-ADC_MUX_DIFF_PIN7_PIN_1_GAIN1
 *25-ADC_MUX_DIFF_PIN0_PIN_2_GAIN1
 *26-ADC_MUX_DIFF_PIN1_PIN_2_GAIN1
 *27-ADC_MUX_DIFF_PIN2_PIN_2_GAIN1
 *28-ADC_MUX_DIFF_PIN3_PIN_2_GAIN1
 *29-ADC_MUX_DIFF_PIN4_PIN_2_GAIN1
 *30-ADC_MUX_DIFF_PIN5_PIN_2_GAIN1
 *31-ADC_MUX_1_22V
 *32-ADC_MUX_0V
 * */
#define ADC_ADMUX_CHANNEL_SELCET 	ADC_MUX_SINGLE_PIN3




/*OPTIONS FOR MODES:
 * 1- ADCSRA_SINGLE_MODE  (SINGLE CONVERSION)
 * 2- ADCSRA_AUTO_MODE (AUTO MODE)
 * */
#define ADC_ADCSRA_MODE_SELECT				ADCSRA_AUTO_MODE



/*OPTIONS FOR TRIGGER MODES (Works only if SYNC MODE IS SELECTED ):
 * 1-SFIOR_FREE_MODE
 * 2-SFIOR_ANALOG_COMPARTOR
 * 3-SFIOR_EXTI_0           		//External Interrupt
 * 4-SFIOR_TIMER0_MATCH
 * 5-SFIOR_TIMER0_OVERFLOW
 * 6-SFIOR_TIMER0_MATCH_B
 * 7-SFIOR_TIMER1_OVERFLOW
 * 8-SFIOR_TIMER1_CAPTURE
 * */
#define ADC_SFIOR_TRIGGER_SELECT			(SFIOR_TIMER0_OVERFLOW<<5)


#endif /* MCAL_ADC_ADC_CONFIG_H_ */
